import {
  ArrowRight,
  Building,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Home,
  LogOut,
  Moon,
  Pizza,
  Search,
  Settings,
  Sun,
  UtensilsCrossed,
  X
} from "lucide-react"

export const Icons = {
  pizza: Pizza,
  home: Home,
  utensilsCrossed: UtensilsCrossed,
  sun: Sun,
  moon: Moon,
  settings: Settings,
  building: Building,
  logOut: LogOut,
  search: Search,
  x: X,
  arrowRight: ArrowRight,
  chevronsLeft: ChevronsLeft,
  chevronLeft: ChevronLeft,
  chevronsRight: ChevronsRight,
  chevronRight: ChevronRight,
}
