import {
  ArrowRight,
  Ban,
  Building,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  DollarSign,
  Home,
  LogOut,
  Moon,
  Pizza,
  Search,
  Settings,
  Sun,
  Utensils,
  UtensilsCrossed,
  X
} from "lucide-react"

export const Icons = {
  pizza: Pizza,
  home: Home,
  utensilsCrossed: UtensilsCrossed,
  utensils: Utensils,
  sun: Sun,
  moon: Moon,
  settings: Settings,
  building: Building,
  logOut: LogOut,
  search: Search,
  x: X,
  arrowRight: ArrowRight,
  chevronsLeft: ChevronsLeft,
  chevronLeft: ChevronLeft,
  chevronsRight: ChevronsRight,
  chevronRight: ChevronRight,
  dollar: DollarSign,
  ban: Ban
}
